platform :ios, '7.0'

pod "AFNetworking", "~> 2.0"
pod 'YTKNetwork'
pod 'RDVTabBarController'
pod 'YTKKeyValueStore'
pod 'FMDB'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'KVOController'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVProgressHUD'
pod 'SDWebImage', '~>3.7'
pod 'IQKeyboardManager'
pod 'ReactiveCocoa' , '2.5'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'ZXingObjC', '~> 3.0'
pod 'pop', '~> 1.0'
pod 'CocoaAsyncSocket'
#pod 'DTCoreText'

#pod 'APAddressBook'
#pod 'Realm/Headers'
#pod 'PayPal-iOS-SDK'
#pod 'CardIO'
#pod 'Tweaks'
#pod 'BlocksKit'
#pod 'CocoaLumberjack'
#pod "MWPhotoBrowser"
#pod 'SlackTextViewController'
#pod "TSMessages"
#pod 'MMDrawerController', '~> 0.5.7'
#pod 'MSDynamicsDrawerViewController'
#pod 'dyci'
#pod 'ECSlidingViewController', '~> 2.0.3'
#pod 'TTTAttributedLabel'
#pod 'RESideMenu', '~> 4.0.7'
#pod 'PNChart'

